### ISSUE TITLE
[BUG] unexpected MidiEndpointConnection.SendMessageWords result

### ISSUE THREAD

**Issue by Bremmers** [microsoft/MIDI#175]
steps:
Call MidiEndpointConnection.SendMessageWords(0, a, b).

Note that timestamp = 0, so the message should be sent immediately

expected:
returns "Succeeded" and "SentImmediately"  (0x80000001)

observed:
returns "Succeeded" and "Other"  (0x81000000)

**Comment by Psychlist1972** [comment]
Thanks Giel

Turns out I won't be able to provide that detail. I was 50/50 on whether or not I could. So I looked through the x-proc code today and it really is just "write to the buffer and return". We only know if it's scheduled or sent immediately once the service reads from the buffer. So completely disconnected process. I'll end up removing those success reasons. It was a good idea :)

But I'm adding unit tests for the error conditions I *can* catch.

**Comment by Psychlist1972** [comment]
BTW, that also means I can't return the SchedulerQueueFull error condition.
