### ISSUE TITLE
[BUG] midi.exe doesn't recognize USB MIDI 1.0 device which uses two or more cables.

### ISSUE THREAD

**Issue by dmiura** [microsoft/MIDI#180]
**Applies To**
midi.exe (or MIDI services?)

**Describe the bug**
midi.exe doesn't recognize USB MIDI 1.0 device which  uses two or more cables.
(midi.exe can recognize device with one cable.)

**To Reproduce**
Please find attached which is a binary file for ProtoZOA firmware.
This firmware is using four cables, midi.exe doesn't recognize this ProtoZOA as USB MIDI 1.0 device.
[SevenColor4.uf2.zip](https://github.com/microsoft/MIDI/files/13784566/SevenColor4.uf2.zip)

**Comment by Psychlist1972** [comment]
Is this with the device set to use the old USB MIDI 1.0 class driver? If so, I know the issue. The device would normally be recognized and configured properly under the new class driver.

**Comment by Psychlist1972** [comment]
The existing logic works like this:

If it's connected to the new class driver, it should be recognized and show up as a bidirectional endpoint regardless of how many cables it has and if it's MIDI 1.0 or MIDI 2.0

If it's a legacy MIDI 1.0 device connected to a third-party MIDI 1.0 driver, or our legacy in-box MIDI 1.0 class driver, the logic looks to see if there are exactly two endpoints and one is in and one is out. If so, it will create a bidirectional endpoint. Otherwise, it creates input and output endpoints, which are no longer exposed via the new API. 

Based on discussions we had at the Redmond event, the second part needs to change. #184

But it shouldn't be "two or more cables". If there are two inputs or two outputs, or a combined number of inputs and outputs greater than two, then you'll run into this (current) limitation. If you are running into it with a device that has a single input and a single output, please let me know.
