### ISSUE TITLE
[BUG] First launch midi.exe, it will not recognize any external devices.

### ISSUE THREAD

**Issue by masahirokakishita** [microsoft/MIDI#400]
**Describe the bug**
When you first launch midi.exe, it will not recognize any external devices.

**To Reproduce**
1) With the PC powered off, connect the ProtoZoA.
2) Restart your PC and launch midi.exe

`>midi endpoint monitor --verbose`

Microsoft Windows MIDI Services Console

Please select an endpoint

  🔁 Diagnostics Loopback A
  🔁 Diagnostics Loopback B
  🔙 (Cancel)
  
ProtoZoA is not recognized.

3)Cancel and launch midi.exe again.
  
`> midi endpoint monitor --verbose`

Microsoft Windows MIDI Services Console

Please select an endpoint

  🎹 ProtoZoA
  🔁 Diagnostics Loopback A
  🔁 Diagnostics Loopback B
  🔙 (Cancel)
  
The second time, midi.exe will recognize ProtoZoA.

**Comment by Psychlist1972** [comment]
Thanks. This is fixed in DP7. The service now waits for enumeration to complete for the two USB transports (KS and KSA) before returning back from the initial activation call.

Demand-start (start the service when it is first called) is a requirement for this to be in-box in Windows. Customers who use MIDI all the time will be encouraged to set the service set to auto-start instead of demand start so there's no delay on first call.

**Comment by Psychlist1972** [comment]
Closed with release of DP7
