### ISSUE TITLE
[BUG]  session.CreateEndpointConnection(); does not return nullptr when called with invalid EndpointID

### ISSUE THREAD

**Issue by MusicMaker** [microsoft/MIDI#429]
**Description**

auto receiveEndpoint = session.CreateEndpointConnection(); does not return nullptr when called with invalid EndpointID

**To Reproduce**

call auto receiveEndpoint = session.CreateEndpointConnection(); with an invalid EndpointID

**Expected behavior**

nullptr returned

**Screenshots**

N/A

**Installer Name or Version**

DP6

**Desktop (please complete the following information):**

  Win 11 Insider Pro Canary 

**Device information, if this is with an external MIDI device:**

 N/A

**Application Information**

C++/WinRT based on SDK sample code.

**Comment by Psychlist1972** [comment]
This is a good point. Right now, the id is only verified once you call `Open()` because that's when the service call is made.

I can add a check for a valid endpoint id, but it's always possible that the endpoint becomes unavailable (usb cable unplugged, etc.) between the create and open, so the return value (boolean) from `Open` always needs to be checked.

The reason this is a two-step process is you need to be able to set up event handlers and processing objects/listeners before opening the connection.

**Comment by Psychlist1972** [comment]
Fixed in upcoming DP8. The code now checks to see if the endpoint id is a valid Windows MIDI Services id, and then checks to see if the endpoint interface has been activated. Returns nullptr if fails either check.

Note that you can still disconnect a device between endpoint connection creation and opening. In that case, you will get a failure when you try to open it.

**Comment by Psychlist1972** [comment]
In DP8
