### ISSUE TITLE
[BUG] Windows service to respond to UMP Stream Configuration requests

### ISSUE THREAD

**Issue by MusicMaker** [microsoft/MIDI#440]
**Description**

Page 37 of the UMP 1.1.1 specification describes that a device can request a configuration request.

Upon sending 
F0050103 00000000 00000000 00000000 Stream (0F) Endpoint Stream Configuration Request Complete, Protocol 0001h, Jitter 03h
The Windows service does not respond to such request.

**Describe the solution you'd like**
Respond to stream configuration requests

**Alternatives considered**
N/A

**Comment by Psychlist1972** [comment]
Is this with the same device where function block changes sent to the service are not being processed after initial negotiation? If so, may be the same issue. I'll need to see if there's some disconnection happening.

Changed to bug because there's code in the service to handle the stream configuration request.

**Comment by MusicMaker** [comment]
AFAIK see with DP7 and latest driver, the function block name and endpoint name notification send to the host AFTER initial negotiation initialized by the host ARE correctly recognized by the service, but info messages (for details, see the other github issue) and stream configuration requests (this issue) are not.

**Comment by Psychlist1972** [comment]
You are correct. Looking at the code, no response is sent unless the service disagrees with the configuration. This is fixed for DP8.

**Comment by Psychlist1972** [comment]
In DP8
