### ISSUE TITLE
[BUG] MidiSrv enumerates redundant/wrong ports if the device consists of multiple KS filter.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#456]
**Describe the bug**
As described in the following feedback, third party's custom driver may instantiate multiple KS filter for MIDI 1.0 device.

https://github.com/microsoft/MIDI/issues/305

With such devices, MidiSrv may enumerate redundant or wrong legacy ports.

**To Reproduce**
1. To enable MidiSrv enumerated ports, make sure the wdmaud2.drv is registered.
2. Download & install the Roland A-Series Keyboard driver:
https://www.roland.com/global/support/by_product/a-49/updates_drivers/4506be14-ffe5-4beb-8064-48ddf78fe56a/
3. Attach the Roland A-49 keyboard to PC and make sure the device is working with the installed custom driver.
4. Run 'midi.exe enum legacy'.

"A-Series Keyboard O-1" and "A-Series Keyboard I-1" are duplicated.
The output port "A-Series Keyboard MIDI OUT" is also enumerated as the input port with the name of "A-Series Keyboard MIDI OUT I-1".

![Image](https://github.com/user-attachments/assets/ad011d5b-060c-4125-a107-1fcc183abad6)

**Expected behavior**
There are no redundant ports and no ports with the wrong direction.

**Screenshots**
![Image](https://github.com/user-attachments/assets/8e9dfa69-1b54-4444-8b1d-3379a5c9c1ff)

**Installer Name or Version**
Windows.MIDI.Services.In-Box.Service.-.1.0.1-preview.7.24305.1438-x64.exe

**Desktop (please complete the following information):**
- OS: Windows 11 24H2 build 26120.2215 (Insider Dev channel)

**Device information, if this is with an external MIDI device:**
- Device: Roland A-49 keyboard
- Driver: Roland A-Series Keyboard driver

**Application Information**
- midi.exe
- WinMM apps

**Comment by Psychlist1972** [comment]
This should be fixed in DP8. I spent the time today to redo the aggregate (KSA) enumeration so it goes through devices rather than filters. It makes it slightly less efficient, but the end result is more what folks will expect to see, and it also eliminates the issues created by having a KS filter-per-port.

Here are the new generated Group Terminal Blocks for a vendor-driver device, the MOTU Express 128. It reports each port # as its own KS filter.

![Image](https://github.com/user-attachments/assets/8d9fdce0-1fcf-47c9-a301-64bccc16f6d1)

There are still some bugs to work out, but the enumeration piece is largely complete other than fixing GTB numbers, and dealing with the auto-generated pin names our USB/KS stack creates, like these:

![Image](https://github.com/user-attachments/assets/ae008ec2-6a37-4b1e-9706-bf2f8a8c5e70)

This change also makes it so the actual endpoint name is the name of the device itself, if the user doesn't override it.

![Image](https://github.com/user-attachments/assets/af1e0f6f-de47-4632-a4df-d79607ae21fc)

I have an A-88 here, but it's in MIDI 2.0 mode at the moment. I'll test it later, as I assume it will respond in the same way the A-49 does.

The naming for WinMM ports is still being worked on as it is far more restrictive, but we will use these generated GTB names as the starting point, adding the direction and group #, and truncating to 32 characters as required.

**Comment by Psychlist1972** [comment]
In DP8
